[package]
name = "uriparser-sys"
version = "0.1.0"
authors = ["Marli Frost <marli@frost.red>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
bindgen = "0.57.0"
cmake = "0.1.45"